FROM node:16

WORKDIR /app

ARG MONGOURI_ARG
#ARG JWTSECRET_ARG
#ARG JWTEXPIRE_ARG
ARG TMDB_ARG

ENV MONGO_URI=${MONGOURI_ARG}
#ENV JWT_SECRET = ${JWTSECRET_ARG}
#ENV JWT_EXPIRE_TIME = ${JWTEXPIRE_ARG}
ENV TMDB_KEY=${TMDB_ARG}

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start"]